
8000 8100 2900
[2023-09-08 11:13:21,244][main.py][line:44][INFO] loading pretrained checkpoint from ./ckpt/original__8636.pkl.
[2023-09-08 11:13:21,273][main.py][line:44][INFO] loading pretrained checkpoint from ./ckpt/ucf_trans_2022.pkl.
[2023-09-08 11:13:21,296][main.py][line:284][INFO] total params:1.2091M
[2023-09-08 11:13:21,296][main.py][line:287][INFO] Training Mode
[2023-09-08 11:13:26,889][main.py][line:151][INFO] Random initialize AUCAUC:0.8636 Anomaly AUC:0.69742
[2023-09-08 11:13:30,928][main.py][line:154][INFO] Random initialize AUCAUC:0.8695 Anomaly AUC:0.70773
  0%|                                                                                                                                                                                                                     | 0/8100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/yukaneko/dev/AbnormalDetection/PEL4VAD/main.py", line 323, in <module>
    main(cfg)
  File "/home/yukaneko/dev/AbnormalDetection/PEL4VAD/main.py", line 289, in main
    train(pel_model, ur_model, train_nloader, train_aloader, test_loader, gt, logger)
  File "/home/yukaneko/dev/AbnormalDetection/PEL4VAD/main.py", line 160, in train
    index_list, frame_num_dict = make_new_dataset(pel_model, ur_model, train_aloader, 0.9)
  File "/home/yukaneko/dev/AbnormalDetection/PEL4VAD/main.py", line 71, in make_new_dataset
    for i, (v_input, _, _, _, Idlist) in enumerate(data_bar):
ValueError: not enough values to unpack (expected 5, got 4)