
8000 8100 2900
[2023-09-09 20:45:57,196][main.py][line:165][INFO] total params:7.5400M
[2023-09-09 20:45:57,197][main.py][line:168][INFO] Training Mode
[2023-09-09 20:45:57,197][main.py][line:78][INFO] Model:XModel(
  (self_attention): XEncoder(
    (self_attn): TCA(
      (q): Linear(in_features=1024, out_features=128, bias=True)
      (k): Linear(in_features=1024, out_features=128, bias=True)
      (v): Linear(in_features=1024, out_features=128, bias=True)
      (o): Linear(in_features=128, out_features=1024, bias=True)
      (act): Softmax(dim=-1)
    )
    (linear1): Conv1d(1024, 512, kernel_size=(1,), stride=(1,))
    (linear2): Conv1d(512, 300, kernel_size=(1,), stride=(1,))
    (dropout1): Dropout(p=0.1, inplace=False)
    (dropout2): Dropout(p=0.1, inplace=False)
    (norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    (loc_adj): DistanceAdj()
    (DR_DMU): WSAD(
      (embedding): Temporal(
        (conv_1): Sequential(
          (0): Conv1d(1024, 512, kernel_size=(3,), stride=(1,), padding=(1,))
          (1): ReLU()
        )
      )
      (triplet): TripletMarginLoss()
      (Amemory): Memory_Unit(
        (sig): Sigmoid()
      )
      (Nmemory): Memory_Unit(
        (sig): Sigmoid()
      )
      (selfatt): Transformer(
        (layers): ModuleList(
          (0-1): 2 x ModuleList(
            (0): PreNorm(
              (norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
              (fn): Attention(
                (attend): Softmax(dim=-1)
                (to_qkv): Linear(in_features=512, out_features=2048, bias=False)
                (to_out): Sequential(
                  (0): Linear(in_features=1024, out_features=512, bias=True)
                  (1): Dropout(p=0.1, inplace=False)
                )
              )
            )
            (1): PreNorm(
              (norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
              (fn): FeedForward(
                (net): Sequential(
                  (0): Linear(in_features=512, out_features=512, bias=True)
                  (1): GELU(approximate='none')
                  (2): Dropout(p=0.1, inplace=False)
                  (3): Linear(in_features=512, out_features=512, bias=True)
                  (4): Dropout(p=0.1, inplace=False)
                )
              )
            )
          )
        )
      )
      (encoder_mu): Sequential(
        (0): Linear(in_features=512, out_features=512, bias=True)
      )
      (encoder_var): Sequential(
        (0): Linear(in_features=512, out_features=512, bias=True)
      )
      (relu): ReLU()
    )
  )
  (classifier): Conv1d(300, 1, kernel_size=(9,), stride=(1,))
  (dropout): Dropout(p=0.1, inplace=False)
)
[2023-09-09 20:45:57,197][main.py][line:79][INFO] Optimizer:AdamW (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    initial_lr: 0.0001
    lr: 0.0001
    maximize: False
    weight_decay: 0.01
)
[2023-09-09 20:46:05,362][main.py][line:82][INFO] Random initialize AUCAUC:0.5802 Anomaly AUC:0.50318
[2023-09-09 20:46:23,782][main.py][line:106][INFO] [Epoch:1/100]: lr:0.00010 | loss1:0.5795 loss2:1.2456 loss3:0.3798 | AUC:0.7981 Anomaly AUC:0.6067
[2023-09-09 20:46:42,030][main.py][line:106][INFO] [Epoch:2/100]: lr:0.00010 | loss1:0.1162 loss2:0.8933 loss3:0.3105 | AUC:0.8096 Anomaly AUC:0.6699
[2023-09-09 20:47:00,815][main.py][line:106][INFO] [Epoch:3/100]: lr:0.00010 | loss1:0.0512 loss2:0.7853 loss3:0.2483 | AUC:0.8259 Anomaly AUC:0.6633
[2023-09-09 20:47:19,468][main.py][line:106][INFO] [Epoch:4/100]: lr:0.00010 | loss1:0.0416 loss2:0.7155 loss3:0.2048 | AUC:0.8165 Anomaly AUC:0.6514
[2023-09-09 20:47:38,197][main.py][line:106][INFO] [Epoch:5/100]: lr:0.00010 | loss1:0.0860 loss2:0.6344 loss3:0.1580 | AUC:0.8055 Anomaly AUC:0.6496
[2023-09-09 20:47:57,085][main.py][line:106][INFO] [Epoch:6/100]: lr:0.00010 | loss1:0.0626 loss2:0.5704 loss3:0.1176 | AUC:0.8329 Anomaly AUC:0.6431
[2023-09-09 20:48:15,989][main.py][line:106][INFO] [Epoch:7/100]: lr:0.00010 | loss1:0.0492 loss2:0.5211 loss3:0.0881 | AUC:0.8312 Anomaly AUC:0.6159
[2023-09-09 20:48:34,866][main.py][line:106][INFO] [Epoch:8/100]: lr:0.00010 | loss1:0.4527 loss2:0.9795 loss3:0.4200 | AUC:0.5593 Anomaly AUC:0.5275
[2023-09-09 20:48:53,823][main.py][line:106][INFO] [Epoch:9/100]: lr:0.00010 | loss1:0.0493 loss2:0.7540 loss3:0.2358 | AUC:0.7199 Anomaly AUC:0.5568
[2023-09-09 20:49:12,681][main.py][line:106][INFO] [Epoch:10/100]: lr:0.00010 | loss1:0.0282 loss2:0.6778 loss3:0.1555 | AUC:0.7661 Anomaly AUC:0.5604
Exception ignored in: <function _releaseLock at 0x7f16a9511870>
Traceback (most recent call last):
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/logging/__init__.py", line 228, in _releaseLock
    def _releaseLock():
KeyboardInterrupt:
Exception in thread Thread-35 (_pin_memory_loop):
Traceback (most recent call last):
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/multiprocessing/connection.py", line 757, in answer_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/queue.py", line 179, in get
    raise Empty
_queue.Empty
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/yukaneko/dev/AbnormalDetection/PEL4VAD/main.py", line 203, in <module>
    main(cfg)
  File "/home/yukaneko/dev/AbnormalDetection/PEL4VAD/main.py", line 170, in main
    train(model, train_nloader, train_aloader, test_loader, gt, logger)
  File "/home/yukaneko/dev/AbnormalDetection/PEL4VAD/main.py", line 90, in train
    loss1, loss2, cost = train_func(train_nloader, train_aloader, model, optimizer, criterion, criterion2, criterion3, logger_wandb, args.lamda, args.alpha)
  File "/home/yukaneko/dev/AbnormalDetection/PEL4VAD/train.py", line 13, in train_func
    for i, ((v_ninput, t_ninput, nlabel, multi_nlabel), (v_ainput, t_ainput, alabel, multi_alabel)) \
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1284, in _get_data
    success, data = self._try_get_data()
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1145, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 657772, 657773, 657774, 657775, 657776, 657777, 657778, 657779) exited unexpectedly