[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m Attempted to change value of key "dataset" from ucf to ucf-crime
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m If you really want to do this, pass allow_val_change=True to config.update()
Traceback (most recent call last):
  File "/home/yukaneko/dev/AbnormalDetection/PEL4VAD/main.py", line 323, in <module>
    main(cfg)
  File "/home/yukaneko/dev/AbnormalDetection/PEL4VAD/main.py", line 242, in main
    logger_wandb.config.update(cfg.__dict__)
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 184, in update
    sanitized = self._update(d, allow_val_change)
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 237, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/yukaneko/miniconda3/envs/detection/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 258, in _sanitize
    raise config_util.ConfigError(
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "dataset" from ucf to ucf-crime
If you really want to do this, pass allow_val_change=True to config.update()